"""Central configuration and constants for ctiforge."""

from __future__ import annotations

import os
from pathlib import Path

# LLM defaults. API key is read from the environment ONLY — never a config file,
# never logged.
DEFAULT_MODEL = "claude-sonnet-4-6"
API_KEY_ENV = "ANTHROPIC_API_KEY"
MODEL_ENV = "CTIFORGE_MODEL"

# ATT&CK dataset (official MITRE CTI repo, enterprise domain).
ATTACK_URL = (
    "https://raw.githubusercontent.com/mitre/cti/master/"
    "enterprise-attack/enterprise-attack.json"
)
CACHE_MAX_AGE_DAYS = 30

# Ingest guardrail: reject near-empty extractions.
MIN_TEXT_CHARS = 500

# Analyze: chunk boundary for long reports.
CHUNK_THRESHOLD_CHARS = 40_000

# Banner stamped on every output: the analysis is machine-drafted.
REVIEW_BANNER = (
    "MACHINE-DRAFTED ANALYSIS — REQUIRES HUMAN REVIEW. "
    "Indicators are deterministically extracted; the narrative, ATT&CK mappings, "
    "and indicator context below are generated by an LLM and may contain errors."
)


def cache_dir() -> Path:
    """Return the ctiforge cache directory, creating it if needed."""
    base = os.environ.get("XDG_CACHE_HOME") or os.path.join(Path.home(), ".cache")
    d = Path(base) / "ctiforge"
    d.mkdir(parents=True, exist_ok=True)
    return d


def resolve_model(cli_model: str | None) -> str:
    """Resolve the model: CLI flag > env var > default."""
    return cli_model or os.environ.get(MODEL_ENV) or DEFAULT_MODEL


def get_api_key() -> str | None:
    """Read the Anthropic API key from the environment only."""
    return os.environ.get(API_KEY_ENV)
